name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      metadata:
        image: kwizapp/metadata-service:latest
        ports:
          - 3003
        env:
          DATABASE_URL: $(secrets.DATABASE_URL)
          POSTER_SERVICE_URL: http://localhost:3002
          PORT: 3003
      poster:
        image: kwizapp/poster-service:latest
        ports:
          - 3002
        env:
          API_KEY: $(secrets.POSTER_API_KEY)
          PORT: 3002

    steps:
      - uses: actions/checkout@v2
      - name: Replace .npmrc with the CI-ready version
        run: rm .npmrc && mv .npmrc.ci .npmrc
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@kwizapp'
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm run format:ci
      - run: npm run typings:generate
      - run: npm test
        env:
          METADATA_SERVICE_URL: http://localhost:${{ job.services.metadata.ports[3003] }}
          POSTER_SERVICE_URL: http://localhost:${{ job.services.poster.ports[3002] }}
          CI: 'true'
  # build image for docker hub (kwizapp/)
  build_docker_hub:
    runs-on: ubuntu-latest
    needs: test # required that this step has completed

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build the Docker image (prod)
        run: docker build -f Dockerfile.prod . --tag kwizapp/nest-api:latest --build-arg NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Push the Docker image to Docker Hub
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        run: docker push kwizapp/nest-api

  # --- STAGING ---
  build_stage:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev'

    steps:
      - uses: actions/checkout@v2
      - name: Pull the latest image from Docker Hub
        run: docker pull kwizapp/nest-api:latest
      - uses: azure/docker-login@v1
        with:
          login-server: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Build the Docker image
        run: docker build -f Dockerfile.prod . --cache-from kwizapp/nest-api:latest --tag registry.heroku.com/kwiz-nest-api-stage/web --build-arg NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Push the Docker image to Heroku
        run: docker push registry.heroku.com/kwiz-nest-api-stage/web

  deploy_stage:
    runs-on: ubuntu-latest
    needs: [test, build_stage]
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Login to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login
      - name: Release the new version
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a kwiz-nest-api-stage web

  # --- PRODUCTION ---
  build_prod:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: Pull the latest image from Docker Hub
        run: docker pull kwizapp/nest-api:latest
      - uses: azure/docker-login@v1
        with:
          login-server: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Build the Docker image
        run: docker build -f Dockerfile.prod . --cache-from kwizapp/nest-api:latest --tag registry.heroku.com/kwiz-nest-api/web --build-arg NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Push the Docker image to Heroku
        run: docker push registry.heroku.com/kwiz-nest-api/web

  deploy_prod:
    runs-on: ubuntu-latest
    needs: [test, build_prod]
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Login to Heroku
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login
      - name: Release the new version
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a kwiz-nest-api web
